# Generated by Django 4.2 on 2024-10-06 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{4}-[0-9]{3}-[0-9]{2}-[0-9]{2}$",
                        "Enter a valid phone number.",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
