# Generated by Django 4.2 on 2024-10-13 18:18

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[utils.validators.PhoneNumberValidator()],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[utils.validators.UsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
