# Generated by Django 4.2 on 2024-09-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Audio file"), (2, "Video file"), (3, "PDF file")],
                default=2,
                verbose_name="file type",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="category/", verbose_name="avatar"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="products.product",
                verbose_name="product",
            ),
        ),
    ]
